name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-pr-message: 'Work on this PR is stalled. It will automatically be closed if the ticket is not updated.'
          close-pr-message: 'This PR has been closed because the original author has abandoned work on it.'
          days-before-stale: -1
          days-before-pr-stale: 7
          days-before-pr-close: 1
          stale-issue-label: 'stale'
          exempt-issue-labels: 'needs-triage,needs-review,backlog'
          stale-pr-labels: 'stale'
          exempt-pr-labels: 'wip'